### ISSUE TITLE
Update for Bevy 0.6 please

### ISSUE THREAD

**Issue by pyweeker** [belzile/platformer#11]
hello Belzile , possible to get it for Bevy 0.6 ? spritesheet animation ?
Maybe it will be platformers for next bevy game jam  [ https://itch.io/jam/bevy-jam-1]( https://itch.io/jam/bevy-jam-1
)

**Comment by belzile** [comment]
> possible to get it for Bevy 0.6 ?

The code in the repository has been updated to Bevy 0.6. I am not (short term) planning to update my tutorial though.

The main differences from Bevy 0.5 is that components need to derive the component trait (add `#[derive(Component)]` on top of the struct).

UI stuff changed more. You need to inject a color instead of a material, and the property is not in the same place.

Otherwise the job to do is mostly adding `.into()` to convert a couple structs.

Anyway, you can still refer to the updated code (on the master branch) if you are stuck.

> spritesheet animation ?

That would be a good topic for another article. I will think about it.
